### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#1]
We need to create milestone being set for this project

**Comment by himynameisdave** [comment]
+1 :+1:

**Comment by stephenway** [comment]
:+1:

**Comment by marcustisater** [comment]
I am not going to do anything fancy so will end up creating a bunch of issues and grouping them in order priority of milestones. Important stuff goes into Sprint 1 then Sprint 2 etc... This will also build a process of time line on what has to be completed first.
