### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#10]
@ai do you think it's possible to get up an staging server for tests when we start building the website? How is that part looking? Do you think that's necessary? It would be cool with some kind of a beta launch also

**Comment by ai** [comment]
Do we need something more, that static server.

GitHub Pages is OK for static. For more, I can ask Evil Martians.

**Comment by marcustisater** [comment]
Yeah I figured we wait for #8 to settle first.

**Comment by MoOx** [comment]
Github pages will be more than enough for Statinamic ;)

**Comment by marcustisater** [comment]
Great, I will set it up when there is some content to show as staging. 

@ai are you considering using GitHub pages when the website goes live too?

**Comment by ai** [comment]
@marcustisater yeap, GitHub Pages is fast and free :)

**Comment by marcustisater** [comment]
Awesome, I think a cool idea would be to create a subdomain like **beta.postcss.com** when we have something to show if you would like to have it public otherwise we can add robots and have it only available here to find.

**Comment by MoOx** [comment]
I don't think it's a big deal that a WIP is public (on postcss.com, not under a subdomain). The main thing is just to not share the link until you consider it's "good enough".

**Comment by ai** [comment]
Yeap, I think too that we can put content directly to `postcss.com`, because any content is good for PostCSS

**Comment by stephenway** [comment]
I would caution that the beta subdomain might get indexed unless it's in it's own repo without a master branch. http://stackoverflow.com/questions/15844905/how-to-stop-google-indexing-my-github-repository

Of course indexing a site with the same or similar content could lead to search engines marking your site as duplicate content. Unless you want to canonicalize the beta site.

**Comment by marcustisater** [comment]
:+1:

**Comment by marcustisater** [comment]
#31
