### ISSUE TITLE
Collection of ideas

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#11]
We are going to try end up having all initial suggestions for the website collected here. Try reference tickets to this one.

@ai had some very good suggestions from ticket [#391](https://github.com/postcss/postcss/issues/391)

> Plugins list (even with search like in gulp) is a lame way. We need some wizard (of course list will exists too):
You select basement: preprocessors or/and CSS4.
You select architecture: BEM, CSS Modules, etc.
You select a builder: Gulp, webpack, grunt, etc.
Pick some extra sugar.
We will get you a exactly code to copy-paste to your build process. For example, only gulp-cssnext with some sugar plugin additions if you select CSS4, BEM, Gulp and not so many additions.
AST explorer for plugin developer. You put a CSS and get PostCSS AST with references.
Migration guide
Docs with good formation.
Playground based on postcss-use.

**Comment by ai** [comment]
Playground can be replaced by [AST Explorer](http://astexplorer.net/). They have PostCSS support and it the best.

@RReverser @fkling is it possible to include AST Explorer to other site? @marcustisater do wwe need it? :)

**Comment by fkling** [comment]
@ai: Not yet, but I have an issue open for that: https://github.com/fkling/astexplorer/issues/70 . Happy to work on this and open to suggestions.

**Comment by marcustisater** [comment]
I think it's a great idea of adding AST Explorer to the website to the section of "How to create you're first PostCSS Plugin". We can also leave it as an hyperlink if embedding is not possible.

**Comment by fkling** [comment]
I started working on something that lets you specify the parser in the URL. That should be good enough for a start I guess.

**Comment by marcustisater** [comment]
I will break this ticket down into several ones then we can decide on what gets implemented and what not. I will also wait for #4 to finish off here. 

If there any more ideas, that can be created into more issues labeld as **dicussion** or **question**
