### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#13]
Boilerplate to be started when #8 is completed. What I mean by boilerplate is to add things like well documented and thought out structured CSS, JS before we get to building. 

Should we consider to use structure like BEM or just plain up components with CSS Modules etc...  

Assignee: **TBA** Lead Developer to help out?

**Comment by mxstbr** [comment]
Sorry, misclicked and closed the issue on accident. 

I'd say let's go with components + CSS modules, it's the future and PostCSS fits perfectly with it.

**Comment by ai** [comment]
Do not forget about `all: initial` and postcss-autoreset. Global reset and inherited properties is a problem too.

**Comment by MoOx** [comment]
I can setup the boilerplate for Statinamic, that will help me review statinamic doc + enhance the `setup` command.
Note: Statinamic default boilerplate provides css modules.

**Comment by mxstbr** [comment]
@MoOx can we do it together/can you walk me through it? Haven't worked with Statinamic at all.

**Comment by MoOx** [comment]
Here is a start http://moox.io/statinamic/docs/setup/
That should help.
I think I need to add more stuff based on a discussion with someone in reactiflux.
Meanwhile, if you want to try this now, feel free to ask all the question you got as Github issues in Statinamic repo for now :)

**Comment by mxstbr** [comment]
@MoOx Cheers, will take a look!

**Comment by marcustisater** [comment]
Great, feel free to override README with documentation of how to to get Statinamic up and running locally once it's up.

**Comment by MoOx** [comment]
"npm start" will be enough for local usage.

For "production" (build + commit to github pages - gh-pages branch) we will need to follow (once) instructions of statinamic docs to automate deploy on each commit pushed to master. I can help for that.

**Comment by mxstbr** [comment]
Let's do that and make master protected and only be committed into via PRs for safety.

If all you are going to do is the setup thing in the Statinamic docs, I can submit a PR as well.

**Comment by MoOx** [comment]
Feel free to do it @mxstbr ;)

**Comment by marcustisater** [comment]
Agreed @mxstbr that's already set to default. PR needs to be reviewed before merged into master.

@mxstbr can you setup the initial files to master then we can go from there with setting up more files if needed.

**Comment by MoOx** [comment]
@mxstbr if you need assistance, do not hesitate to use Statinamic support (me haha). I plan to work on this project for the incoming weeks/months.

**Comment by mxstbr** [comment]
@marcustisater will do! 

@MoOx thanks, if I run into problems I'll submit issues!

**Comment by mxstbr** [comment]
Very initial setup done, will take a deeper look tomorrow!

**Comment by MoOx** [comment]
Do not hesitate to tell me how bad your experience was (because currently I think it's not really convenient...) and what we should improve. Feedbacks are important to me.

**Comment by marcustisater** [comment]
Can someone double check this for me #16? Thanks.

**Comment by mxstbr** [comment]
Need a better webpack config maybe

**Comment by MoOx** [comment]
I think I will include postcss-cssnext in the default boilerplate but that won't be good for everybody.
Anyway, that's the power of statinamic: you define what you want/need.
Here is an example of another config https://github.com/putaindecode/putaindecode.io/blob/master/scripts/build.js

**Comment by marcustisater** [comment]
Discussion from the meeting is to get the boilerplate ready before #12 is completed and also provide more documentation - #28

**Comment by mxstbr** [comment]
I think it makes sense to separate available layouts (e.g. `Page`, `PageError`,...) from more general React components (e.g. `Button`, `Footer`,...) by putting them in a separate folder.

**I suggest we call the folder `web_modules/pages` for the layouts and `web_modules/components` for more general components.**

*`routes` was another option I was thinking about, but I'm pretty sure for beginners the connection between the URL and the component is clearer if the folder is called `pages`.*

Thoughts? (Maybe worth including that separation in the official boilerplate @MoOx?)

**Comment by MoOx** [comment]
What about this (I use it on a website and I like it)

- web_modules/* for components
- web_modules/layouts/* for layouts components ?

**Comment by mxstbr** [comment]
:+1: I like it!

**Comment by mxstbr** [comment]
When #45 is reviewed and merged, this issue can be closed as the boilerplate setup is done for now. There will highly likely be small improvements over time, but the current state is enough for beginning to work on the actual site.

**Comment by marcustisater** [comment]
Yup, sounds good. Nice work.

**Comment by marcustisater** [comment]
Closed?

**Comment by mxstbr** [comment]
Oh yeah sorry, forgot to close the Issue!
