### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by stephenway** [postcss/postcss.com#14]
We already have the logo symbol but do not have a logotype to go with it. I would think this would be a requirement for a website. Would love to track this here and collectively look at type specimens and usage. 

<img width="179" alt="screen shot 2015-12-31 at 4 31 33 pm" src="https://cloud.githubusercontent.com/assets/38894/12069292/085203de-afdc-11e5-9720-cfd9fca7767f.png">

First comp from today, just basic Helvetica Neue

**Comment by marcustisater** [comment]
Yes I agree with you, great point. 

@ai do we have any specific styleguide to go after when it comes to font, colors etc?

**Comment by ai** [comment]
@stephenway looks like very nice. Maybe we should cappitalize “CSS” to? Like PostCSS?

**Comment by ai** [comment]
Styleguide is simple: Middle Ages and alchemy. But, of course, we should not use medieval font. Just few references.

**Comment by MoOx** [comment]
What about using a typo like the effect on the logo:

![screen shot 2016-01-02 at 19 54 42](https://cloud.githubusercontent.com/assets/157534/12075739/b31b905a-b18a-11e5-9e72-f4155a8ac007.png)

**Comment by stephenway** [comment]
@MoOx That idea would depend on if the logo symbol was intended to have an "o" inside it. Mixing the symbol into the logotype makes it hard to separate the two.

**Comment by MoOx** [comment]
Yeah sure, that was just an idea ^^

**Comment by marcustisater** [comment]
haha, that's funny. 

@ai Great, maybe we can form an styleguide after the design is completed as well and double check everything so it's according to what you had in mind.

**Comment by stephenway** [comment]
Yea style guide would be a great for adding to the website and improving communication with the community.

**Comment by marcustisater** [comment]
Yeah indded, It would be cool doing something similar to [lonleyplanet](http://rizzo.lonelyplanet.com/styleguide/design-elements/colours) or maybe we can use [postcss-styleguide](https://github.com/morishitter/postcss-style-guide) :wink:

**Comment by MoOx** [comment]
Maybe this would be even more appropriate https://github.com/sapegin/react-styleguidist (and logical)

**Comment by stephenway** [comment]
I've used that and ended up migrating to Jon's mdcss, absolutely happy with it. Comes with lots of options.

**Comment by marcustisater** [comment]
That looks neat, we should definitely try that one out.

**Comment by stephenway** [comment]
Maybe we should make a new issue for this? Agreed @MoOx

**Comment by marcustisater** [comment]
Absolutely, that's my job to do :sweat_smile:

**Comment by marcustisater** [comment]
Anyway, logo looks great to me but as @ai pointed out maybe make the CSS text a little big bigger and try that with the same red color if you mind @stephenway.

**Comment by stephenway** [comment]
Yea I want to post some more options asap

**Comment by ai** [comment]
PostCSS sign is not good for “o”. Because it can be read as “A” to because of triangle.

**Comment by stephenway** [comment]
This is an overview of the first type exploration from today, I've bordered 2 I think work nicely when paired with the logo symbol. 

![postcss-logotype-options](https://cloud.githubusercontent.com/assets/38894/12076420/0c3ca384-b160-11e5-9781-f09ef35e897c.png)

**Comment by MoOx** [comment]
The third lgtm :)

**Comment by stephenway** [comment]
@MoOx  That's using [Google's Poppins](https://www.google.com/fonts/specimen/Poppins) font.

**Comment by ai** [comment]
4th in right is a Cyrillic reference? :D 

http://i.kinja-img.com/gawker-media/image/upload/s--GSNBcS9r--/c_scale,fl_progressive,q_80,w_800/18j1kyfaz7pb7jpg.jpg

**Comment by marcustisater** [comment]
Great work, the third or seventh in my opinion.

**Comment by stephenway** [comment]
@ai Cyrillic, yes, kinda failed on getting a good "T", but I think it's readable. Maybe need to substitute with a "T" from another font?

**Comment by marcustisater** [comment]
but on the other hand I agree with the choice of number duo: 

> Styleguide is simple: Middle Ages and alchemy.

**Comment by ai** [comment]
Guys, do you want a crazy idea? There is a very strange medieval way to write a letters.

https://s-media-cache-ak0.pinimg.com/originals/40/84/db/4084dbadc95d6f95bbe07e0e330c752f.gif
http://eldesign.ru/upload/Image/sreda/2007-05-23/letter_r08.gif
https://s-media-cache-ak0.pinimg.com/originals/6b/b4/dc/6bb4dc58d61fc8dc7f7e182368dda295.gif

The idea is to combine symbols in calligraphy pattern, like Arabic people do.

But it is hard to do, only if @stephenway really want to make some culture investigations.
I can help you, I often use this way in henna painting:
https://pp.vk.me/c314431/v314431146/4d05/bSv3XtzICu4.jpg
https://pp.vk.me/c621221/v621221146/246aa/HM9skZNRTtU.jpg
https://pp.vk.me/c623429/v623429146/1de5f/FOZ8SJtnI_w.jpg

**Comment by ai** [comment]
@stephenway you can find more by “orthodox calligraphy” or “Vyaz”
http://www.christianforums.com/proxy.php?image=http%3A%2F%2Fmedia-cache-ak0.pinimg.com%2F736x%2F74%2F47%2Fd4%2F7447d42fe887d0a99a360013db21debf.jpg&hash=b4b90ec56d2cb118c9d713f195866376
https://s-media-cache-ak0.pinimg.com/236x/fa/13/e5/fa13e5eadb29f7d7c1047ed0e8dad538.jpg

**Comment by stephenway** [comment]
@ai Those examples are really cool, is that your own henna? I can try drawing some of that for round 2, but I will make sure that we come up with something that is easy to read too.

**Comment by stephenway** [comment]
So far it sounds like we are looking at these options, plus more calligraphic options that I will get going soon for round 2. 
![round-1-choices](https://cloud.githubusercontent.com/assets/38894/12076529/68123644-b163-11e5-8647-eb9c530127d1.png)

**Comment by ai** [comment]
@shinnn nope-nope, pseudo-cyrillic case we can remove. Cyrillic has own special philosophy and mirroring is not a right way :).

**Comment by ai** [comment]
I amd OK with first. Separating “Post” and “CSS” is a good point of view.

**Comment by ai** [comment]
@stephenway yeap, it is my henna, but it is not my paintings. I just copy them from some medieval book. It will be cool, if we try this Vyaz way. Because it is like playing with static React. This PostCSS site project should be a hobby project to test new ideas for us. We have a lot of task in our job to make a common ordinary solution.

**Comment by stephenway** [comment]
Discussion will continue in postcss/brand#3

**Comment by stephenway** [comment]
To all that subscribed and follow this thread. Follow the brand link for our round 2 options posted today.
