### ISSUE TITLE
Include statinamic to package.json

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#16]
I think we need to include the **npm** for the statinamic build to the package.json or am I wrong?

**Comment by marcustisater** [comment]
https://github.com/postcss/postcss.com/commit/e31c9edddfae57567fd8cb801afd54f871fbd4f3

**Comment by marcustisater** [comment]
reopen if it's need fixes..

**Comment by mxstbr** [comment]
Thanks, am currently on the slopes skiing.

**Comment by marcustisater** [comment]
Yeah I was just trying to setup everything locally. have fun! :ski:

**Comment by mxstbr** [comment]
Thanks for trying!
