### ISSUE TITLE
Get together for first project meeting

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#2]
I think a wise idea is to get together on [Hangouts](https://hangouts.google.com/) or [gitter.im](https://www.gitter.im) and talk over some ideas and inputs for this project meanwhile that there are being some tickets & milestones created. 

There is no set date for a meeting yet but plans are after new years when everybody is back home and are ready for some action.

Date to be updated soon and hopefully time zone friendly :sweat_smile:

**Comment by marcustisater** [comment]
8pm GMT

**Comment by mxstbr** [comment]
Maybe we should leave the issue open so people can find it?

**Comment by marcustisater** [comment]
Yes, you are right. I did a quick update on the README file as well.

**Comment by iamstarkov** [comment]
for anybody in europe
20:00 Greenwich Mean Time (GMT) is 21:00 Central European Time (CET)

**Comment by marcustisater** [comment]
Yes, that's correct. Thanks for clearing that out, will do a quick update in the README.

**Comment by marcustisater** [comment]
Thanks for coming, got really good feedback and it was appreciated having this.
