### ISSUE TITLE
Contributing documentation 

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#22]
We need a REAMDE file with documentation of how to contribute.

**Comment by mxstbr** [comment]
Will add more info about the technical side as soon as I've figured out Statinamic myself. :+1:

**Comment by marcustisater** [comment]
Yeah, we need a section as well for code guidelines.

**Comment by marcustisater** [comment]
https://github.com/postcss/postcss.com/blob/master/CONTRIBUTING.md

**Comment by marcustisater** [comment]
Code guidelines and issues label sections is left over to do.

**Comment by mxstbr** [comment]
@marcustisater will you document the issue labels, seeing as you created them?

**Comment by MoOx** [comment]
my 2 cents for labels https://github.com/MoOx/setup/blob/1b712c1f9cb2495585d47c4db6acba0c9558a0ab/dotfiles/zshrc#L234-L235

**Comment by marcustisater** [comment]
Yeah, I need to structure those. Thanks @MoOx

**Comment by marcustisater** [comment]
I updated the labels with some of your's, will document them in the markdown file as well.

**Comment by marcustisater** [comment]
Code guidelines left to do.

**Comment by mxstbr** [comment]
These depend on the solution for #29, will do soon.
