### ISSUE TITLE
Explain Statinamic

### ISSUE THREAD

**Issue by mxstbr** [postcss/postcss.com#28]

**Comment by MoOx** [comment]
Can you elaborate a little bit?

**Comment by marcustisater** [comment]
There is a on-going meeting on gitter right now if you have a few minutes over to join us.

**Comment by marcustisater** [comment]
We had a brief discussion if it would be possible with some more documentation for React/Statinamic. @mxstbr suggested doing a intro webcast about Statinamic, that would most likely involve more people into easing into it.

**Comment by MoOx** [comment]
http://moox.io/statinamic/ should be the reference. If you feel that something is missing (or just have a question) please open an issue on statinamic website.

**Comment by marcustisater** [comment]
Agreed, the main documentation should be on http://moox.io/statinamic/ but we need to referens it from here in a better way.

**Comment by MoOx** [comment]
Sure.

**Comment by MoOx** [comment]
:+1:
