### ISSUE TITLE
linting error

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#29]
There seems to be a problem with npm start with static not working. If this is a Statinamic issue, please recreate the issue on it's repository or refer this one. 

`throw new Error("webpack build failed with errors");`

**Comment by mxstbr** [comment]
@MoOx any ideas?

**Comment by MoOx** [comment]
I know exactly what this is. Currently the boilerplate contains eslint-loader but no eslint config.
So 2 solutions:
- http://moox.io/statinamic/docs/advanced/good-practises/#linting
- or grab some pieces at least this https://github.com/MoOx/eslint-config-i-am-meticulous/blob/master/index.js#L6-L16

```json
{
  "eslintConfig": {
    "parser": "babel-eslint",

    "ecmaFeatures": {
      "modules": true,
      "experimentalObjectRestSpread": true,
    },
    "env": {
      "node": true,
      "browser": true,
      "es6": true,
    },
  }
}
```

Renaming the issue according to this.
I will create a minimal eslint preset and explain why this is useful even if you don't link (at least it check the syntax).

**Comment by MoOx** [comment]
https://github.com/MoOx/statinamic/issues/72

**Comment by mxstbr** [comment]
I see, will fix soon!
