### ISSUE TITLE
Configure the DNS and domain

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss.com#31]
That would be nice to already have this setup :)
Btw, I think www. are should not be used, this provide a 90' feeling and PostCSS is the future, not the past :)

**Comment by ai** [comment]
+1, let’s redirect from `www.postcss.com` to `postcss.com`

**Comment by mxstbr** [comment]
:+1:

**Comment by marcustisater** [comment]
Agreed, I think we need to setup a CNAME file to the repo and add the alias/A-records to DNS provider. I can look into this with some help from @ai with the DNS.

**Comment by MoOx** [comment]
The CNAME should be generated by the build step, like this https://github.com/putaindecode/putaindecode.io/blob/d4cc328c0c2595c605ac8469339f37c6312ddf21/package.json#L79

**Comment by ai** [comment]
yeap, give a settings, I will put them to DNS. Maybe I can dive you a access, but I didn’t know how and I hope DNS confirugation is once-done-task

**Comment by MoOx** [comment]
I have all my domain at Gandi, so I can help with the setup.

**Comment by marcustisater** [comment]
I would be happy to give you the entire task if you have time since I haven't set this up one before with build step generators @MoOx :smile:

**Comment by marcustisater** [comment]
Are you up for it? :blush:

**Comment by MoOx** [comment]
I have to leave my computer, but you can send me the gandi id I can do that later in the evening or tomorrow morning. Or you can add my as the technical contact, I will send you my gandi id in private.

**Comment by marcustisater** [comment]
I'm afraid I don't have the login access to gandi, @ai is the owner of the domain. @ai can you send me the login details or grant @MoOx as tech-support so he can get in touch with them and set this up.

**Comment by ai** [comment]
I aslo have `postcss.ORG`. Should we make a redirect?

**Comment by marcustisater** [comment]
Yeah, I think .org should be redirected as well.

**Comment by ai** [comment]
I gave access to @marcustisater. Seems like Gandi have only one tech contact.

**Comment by marcustisater** [comment]
Wish me luck, hehe.

@MoOx let me get back to you if I need any help. I will try to set this up tomorrow.

**Comment by MoOx** [comment]
I just take a look to my dns config

```
@ 10800 IN A 192.30.252.153
@ 10800 IN A 192.30.252.154
```

**Comment by marcustisater** [comment]
Thank you.

#37 for auto-deploy pr welcome.

**Comment by marcustisater** [comment]
It should be running as soon when DNS has propagated. I have to look at webforwarding for subdomains and www too.

**Comment by MoOx** [comment]
Already working for me.

**Comment by marcustisater** [comment]
Awesome, not for me yet :cry: Is everything working alright for you? I'll start looking at the automatic deployment meanwhile #37

**Comment by MoOx** [comment]
![screen shot 2016-01-08 at 21 52 03](https://cloud.githubusercontent.com/assets/157534/12209276/3047fe26-b652-11e5-9101-586d09af869f.png)

**Comment by MoOx** [comment]
and www redirection to postcss.com like it should.
gh-pages needs some content now :)

**Comment by marcustisater** [comment]
I added some routing with htacess to fix www redirection but I would need that as well in the gh-pages. I guess this has to be added in the scripts section too or is there any other way to do it?

**Comment by MoOx** [comment]
htaccess do not work on gh-pages. It's not that easy :)

**Comment by marcustisater** [comment]
That makes sense, any other suggestion? Can you do this in any other way then hardcoding the domain name?

**Comment by MoOx** [comment]
You already have a redirection from www.postcss.com to postcss.com, what do you need to add? It's not clear for me.

**Comment by marcustisater** [comment]
Ah yeah of course, sorry. It's already fixed by homepage.

**Comment by marcustisater** [comment]
Thanks for the help.
