### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by mxstbr** [postcss/postcss.com#32]
Currently, the entire code follows @MoOx' [eslint-config-i-am-meticulous](https://github.com/MoOx/eslint-config-i-am-meticulous).

To be honest, I don't think it matters which exact style guide we adhere to, as long as we choose one and force eslint to complete successfully before we merge anything into master.

I'd be fine with simply enforcing `eslint-config-i-am-meticulous` since the whole codebase is written like that at the moment and it'll save us time because we don't have to rewrite everything in a new style. Any objections?

> Note: I personally am a big fan of `eslint-config-airbnb` with [three custom rules](https://github.com/mxstbr/react-boilerplate/blob/master/.eslintrc#L13-L17), for an example of React code with that eslint config take a look at [this example file](https://github.com/mxstbr/react-boilerplate/blob/master/js/components/pages/HomePage.react.js).

**Comment by MoOx** [comment]
Currently you do not use this preset and you eslint config don't enforce anything. You just parse with babel parser.
To use my preset, you will need to use this config http://moox.io/statinamic/docs/advanced/good-practises/#linting

**Comment by mxstbr** [comment]
Yeah, I know. :)

If nobody voices an objection to `eslint-config-i-am-meticulous` within 24 hours, I'll simply use that. I think it's the best solution, as it saves time which we don't have to spend to change the entire code style.

/cc @ai @marcustisater what do you think, you fine with `eslint-config-i-am-meticulous`?

**Comment by MoOx** [comment]
If you want to change, most rules can be automatically fix themselves (see eslint --fix option). So no big deal ;)

**Comment by marcustisater** [comment]
`eslint-config-i-am-meticulous` sounds good to me :+1:
