### ISSUE TITLE
Add https://lgtm.co

### ISSUE THREAD

**Issue by mxstbr** [postcss/postcss.com#34]
> Pull Requests are reviewed by members of the team specified in the MAINTAINERS file in your repository and cannot be merged until all approvals are received.

> Approvers comment on the issue with LGTM, looks good to me, indicating their approval to merge the changeset.

This looks very useful for this project, this means without approval of the core maintainers no PR can be merged.

@ai @marcustisater do you want to be in the MAINTAINERS file? You'd have to comment each and every PR then with `LGTM` though.

**Comment by ai** [comment]
Nope :). But I anyway will be around :).

**Comment by MoOx** [comment]
@mxstbr You can customize pattern and accept `:+1:` or anything ;)

**Comment by marcustisater** [comment]
Sure, I think @MoOx could be a good asset too if he has time for it. 

Isn't it good enough if one of the members accepts it, why all? It seems like a lot of work and waiting...

**Comment by mxstbr** [comment]
Mainly so my mistakes don't slip through cracks, but if I'm the only one in the file it doesn't really make sense to have it. :)

**Comment by MoOx** [comment]
You can configure who many I think.

**Comment by marcustisater** [comment]
That's true, maybe we can add some more "validators" that has enough experience to approve code. 

@jonathantneal , @stephenway ?

**Comment by marcustisater** [comment]
I think it's enough if two people in the MAINTAINERS file approves the PR before merge.

**Comment by mxstbr** [comment]
I like that!

**Comment by marcustisater** [comment]
Sounds great, count me in for that.

**Comment by MoOx** [comment]
I can help if we can define me as "optional" (I mean not required all the time)

**Comment by mxstbr** [comment]
@ai can you either add me to the postcss team or enable LGTM for this repo on https://lgtm.co?

**Comment by ai** [comment]
I am in the city. Can I add it today evening, when I will be near my laptop?

**Comment by mxstbr** [comment]
Yeah definitely, don't worry about it!

2016-01-08 16:52 GMT+01:00 Andrey Sitnik <notifications@github.com>:

**Comment by MoOx** [comment]
@ai I just took the liberty to handle this. @mxstbr have been invited.
Btw, github ask to migrate the org to new roles and shit, so I did that. Note that for now (as it was before) everybody is an owner. Trust is key imo :)

**Comment by mxstbr** [comment]
@MoOx thanks, LGTM.co is now enabled for this repo!
