### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by mxstbr** [postcss/postcss.com#35]
Add continous integration so no PR gets merged that doesn't adhere to the common code style (will be defined in #32) and that breaks the build (and the website) in the process.

**Comment by mxstbr** [comment]
Just realized Travis is already enabled, I only need to add a proper `.travis.yml`! https://travis-ci.org/postcss/postcss.com

**Comment by marcustisater** [comment]
Yup, travis-cli is already enabled. You should have access.

**Comment by mxstbr** [comment]
On it
