### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#40]
We would need a favicon - http://realfavicongenerator.net/ 

@stephenway should we include this into the brand repo as well or is it irrelevant?

**Comment by ai** [comment]
@quaritexa made a clean version of logo. Let's take it

https://github.com/postcss/brand/issues/6

**Comment by ai** [comment]
And let's not create too many favicons like many generators do. I think we need only 32 and 192 px sizes.

**Comment by ai** [comment]
Also I think black favicon is cool

**Comment by quaritexa** [comment]
https://www.dropbox.com/sh/jz7kj75l1i9hhbw/AACjNu5EjOdgCX2fUqic6j6Ya?dl=0

**Comment by ai** [comment]
For 192 "iphone" favicon we can use official logo. More details will be even better. But 32px version looks good.

**Comment by marcustisater** [comment]
I think the favicon looks great, really crisp and has good contrast in it but creating a separation between the original logo from the favicon is for me a little bit strange. What are you're thoughts @stephenway?  

Thanks for the quick updates @quaritexa

**Comment by stephenway** [comment]
@marcustisater We should move this issue to the brand repo and draw a smaller version of the official logo.
