### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#5]
We have a [Slack](https://postcsscom.slack.com) group. Slack only allows people with access to an email address at the domains specified by the team's Owner will be able to sign up therefor I have to do the invite only rule.

If you would like to join the Slack Channel please comment down below you're e-mail adress and the invite will be sent to you. You can also send me you're e-mail adress [privately](mailto:marcus.tisater@gmail.com) 

Thank you,

**Comment by jonathantneal** [comment]
jonathantneal@hotmail.com

**Comment by marcustisater** [comment]
We will be doing gitter instead.

https://gitter.im/postcss/postcss.com

**Comment by jonathantneal** [comment]
I noticed there is a postcss.slack.com. Is that owned by us?

**Comment by ai** [comment]
Nope, we uses only Gitter since Slack is not welcome for new users. Hard process with invite, etc

**Comment by marcustisater** [comment]
I created it a long time ago, that's my fault. I will remove the Slack channel, I think it can confuse users. Sorry!

**Comment by marcustisater** [comment]
Aha wait, I created https://postcsscom.slack.com/ for the website project. Someone else have created postcss.slack.com, that's not me. Hmm?
