### ISSUE TITLE
Lint CSS code with stylelint (as part of the boilerplate)?

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss.com#51]
The [boilerplate issue](https://github.com/postcss/postcss.com/issues/13) mentions adding structured CSS. 

Do you want me to submit a PR that adds linting to each component's CSS, using [`stylelint`](https://github.com/stylelint/stylelint) and the [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard)? Although the config won't help enforce the use of CSS Modules, it will catch little coding mistakes like accidental shorthand overrides and invalid hex colours.

As an aside, it's awesome to see [stylelint](https://github.com/stylelint/stylelint) get a mention in the early mock-up designs! :)

**Comment by mxstbr** [comment]
Yeah sure, sgtm!

**Comment by MoOx** [comment]
Good idea
