### ISSUE TITLE
Project Lead

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#6]
I think in order to run a very successful project you need some developers that are willing to put in some extra work/time and take responsibility therefor we should state some key people that can be lead of development and also design.

@ai will of course have the final word of everything but the main focus it to get some people in charge

TBD on [Gitter](https://gitter.im/postcss/postcss.com) upcoming meeting.

**Comment by mxstbr** [comment]
Would love to help, have built postcss.parts and can integrate that if wanted!

**Comment by marcustisater** [comment]
Lovely, would love to talk more about that with you and the others on gitter after new years! I think it's a brilliant idea.

**Comment by jonathantneal** [comment]
@mxstbr, fantastic news! I’d love to see that as well.

**Comment by mxstbr** [comment]
@marcustisater @jonathantneal could you ping me on [twitter](https://twitter.com/mxstbr) when that topic is talked about on Gitter please, I'm skiing at the moment and am seldomly near my chats. Thanks!

**Comment by marcustisater** [comment]
I will let you know, the project is starting the 5th of January and there is also no rush or deadline set. We are just collecting some ideas and input from everyone.

**Comment by stephenway** [comment]
Looking forward to our meeting!

**Comment by marcustisater** [comment]
closing

#2
