### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#8]
The main decision is to agree on what system is going to be used for this website. My first thought was to do this website in like Jekyll or an small CMS system but now after so many people already wanting to contributing and having suggestions I will leave this up for a very open discussion. 

@MoOx has one suggestion of using Statinamic stated in ticket [#391](https://github.com/postcss/postcss/issues/391) 

> Don't know what you plan to use for the engine, but I would be really happy to offer some support for my new engine Statinamic (react based static website generator, that also provide client side optimised navigation).

What do you guys think? Let us know you're thoughts.

**Comment by ai** [comment]
@mxstbr can we run plugins search on client side with any help from server?

**Comment by MoOx** [comment]
statinamic can prerender page during the build step and can also run client side react view (so live search with an api is not an issue)

**Comment by jonathantneal** [comment]
My 2 cents: Let’s not over React.

I’d aim for beauty and simplicity while leveraging the tools of our community.

**Comment by marcustisater** [comment]
I'm all about using more more modern stuff like React but I'd say that **simplicity** is a great point by @jonathantneal because we would want to have a low "learning curve" so more people can contribute something and also not relaying on @MoOx to be around for 24:7.

**Comment by mxstbr** [comment]
@ai yeah, that works.

I love React,  have worked a lot with it (postcss.parts is [written in react](https://github.com/mxstbr/postcss.parts)), and have been meaning to try Statinamic for a project, so I'll +1 that. I'm fine with Jekyll as well though.

**Comment by ai** [comment]
I understand @jonathantneal with this idea of simplicity.

But I really think that we should experiment with React based statis site. Yeap, it will be more complicated. But it is now fun, and hobby site is for fun.

Also we should use 100% isolated components with CSS Modules and postcss-autoreset with `all: initial`, like I told on http://ai.github.io/postcss-isolation/

It is good to show full power of PostCSS on main site.

**Comment by mxstbr** [comment]
@ai :+1:

**Comment by stephenway** [comment]
@ai Exactly, we need to make this website the driving force for all this project has to offer. :+1:

**Comment by marcustisater** [comment]
Alright, let's try out Statinamic. I think we have enough react heroes to make that happen :smile: 

@mxstbr will be leading the development process. TBA upcoming meeting.

**Comment by MoOx** [comment]
I will try to submit a PR this week with a Statinamic default boilerplate.

**Comment by marcustisater** [comment]
#13
