### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.com#9]
@ai how is the domain name looking? It's already bought, I hope you did that? :stuck_out_tongue_winking_eye:

**Comment by ai** [comment]
Ha-ha :). Yeap, I got [postcss.com](https://who.is/whois/postcss.com).

**Comment by marcustisater** [comment]
haha awesome, I just wanted to make sure :wink:

**Comment by mxstbr** [comment]
That would have been awkward, hah!
